insert into market_daily_stats_y2016m03
select
calculated_at::date,
type_id,
station_id,
region_id,
array_agg(extract(epoch from calculated_at)),
array_agg(buy_price_max),
array_agg(buy_price_wavg),
array_agg(buy_price_5pct),
array_agg(buy_price_median),
array_agg(buy_units),
array_agg(buy_orders_price_chg),
array_agg(buy_orders_vol_chg),
array_agg(buy_orders_disappeared),
array_agg(buy_units_vol_chg),
array_agg(buy_units_disappeared),
array_agg(buy_price_wavg_sold),
array_agg(buy_price_min_sold),
array_agg(buy_price_max_sold),
array_agg(sell_price_min),
array_agg(sell_price_wavg),
array_agg(sell_price_5pct),
array_agg(sell_price_median),
array_agg(sell_units),
array_agg(sell_orders_price_chg),
array_agg(sell_orders_vol_chg),
array_agg(sell_orders_disappeared),
array_agg(sell_units_vol_chg),
array_agg(sell_units_disappeared),
array_agg(sell_price_wavg_sold),
array_agg(sell_price_min_sold),
array_agg(sell_price_max_sold),
array_agg(new_sell_orders),
array_agg(new_buy_orders),
array_agg(new_sell_order_units),
array_agg(new_buy_order_units)

from market_order_stats_ts where calculated_at::date < DATE '2016-04-01' group by calculated_at::date, type_id, region_id, station_id;

insert into market_daily_stats_y2016m04
select
calculated_at::date,
type_id,
station_id,
region_id,
array_agg(extract(epoch from calculated_at)),
array_agg(buy_price_max),
array_agg(buy_price_wavg),
array_agg(buy_price_5pct),
array_agg(buy_price_median),
array_agg(buy_units),
array_agg(buy_orders_price_chg),
array_agg(buy_orders_vol_chg),
array_agg(buy_orders_disappeared),
array_agg(buy_units_vol_chg),
array_agg(buy_units_disappeared),
array_agg(buy_price_wavg_sold),
array_agg(buy_price_min_sold),
array_agg(buy_price_max_sold),
array_agg(sell_price_min),
array_agg(sell_price_wavg),
array_agg(sell_price_5pct),
array_agg(sell_price_median),
array_agg(sell_units),
array_agg(sell_orders_price_chg),
array_agg(sell_orders_vol_chg),
array_agg(sell_orders_disappeared),
array_agg(sell_units_vol_chg),
array_agg(sell_units_disappeared),
array_agg(sell_price_wavg_sold),
array_agg(sell_price_min_sold),
array_agg(sell_price_max_sold),
array_agg(new_sell_orders),
array_agg(new_buy_orders),
array_agg(new_sell_order_units),
array_agg(new_buy_order_units)

from market_order_stats_ts where calculated_at::date < DATE '2016-05-01' AND calculated_at::date >= DATE '2016-04-01' group by calculated_at::date, type_id, region_id, station_id;
